### ISSUE TITLE
customer edit not showing address in address list in the bottom.

### ISSUE THREAD

**Issue by ziauddin** [s-cart/core#1]
file name : core/src/Admin/Views/screen/customer_edit.blade.php
line : 462
change : first_address1 to address1

I fixed to so I wish to updated into it core as well. if you like I will contribute on your project.
thanks

**Comment by lanhktc** [comment]
Thanks for report.
Error fixed https://github.com/s-cart/core/commit/a16659be1295f5bca37d6f0e0f6b5a7373316485
