### ISSUE TITLE
[BUG] Shorten the identifier names in tables and installing errors

### ISSUE THREAD

**Issue by ghost** [s-cart/core#9]
Hello!

I used the prefix "master_" and got following error while installing:
[
#ISC003::SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'master_shop_product_attribute_product_id_attribute_group_id_index' is too long (Connection: mysql, SQL: alter table `master_shop_product_attribute` add index `master_shop_product_attribute_product_id_attribute_group_id_index`(`product_id`, `attribute_group_id`))](url)

I do not know why someone has this dreamy idea of using this kilometer long name: 

`master_shop_product_attribute_product_id_attribute_group_id_index`

Such a freedom of length is not permitted in these names. They MUST BE shortned like:

`master_shop_product_attr_pid_attr_gid_idx`

**Comment by ghost** [comment]
Well, I changed the prefix to m_, which is kind of minimum, the installation routine continued beyond 25% onwards (I had to delete all tables created) and could re-install.

Now I got the following error:

[#ISC007::Can not rename file install.php. Please remove or rename it!
](url)

Well, this should be shown before on the left side, while checking permissions, and not during the installation process. Now this is hanging at 85%.

**Comment by s-cart** [comment]
> Hello!
> 
> I used the prefix "master_" and got following error while installing: [ #ISC003::SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'master_shop_product_attribute_product_id_attribute_group_id_index' is too long (Connection: mysql, SQL: alter table `master_shop_product_attribute` add index `master_shop_product_attribute_product_id_attribute_group_id_index`(`product_id`, `attribute_group_id`))](url)
> 
As the message says, the index key is too long, due to limitation in mysql version. Please set shorter prefix.

**Comment by s-cart** [comment]
> Well, this should be shown before on the left side, while checking permissions, and not during the installation process. Now this is hanging at 85%.

You have not set permission to delete/rename the install.php file. But you can do this manually (delete install.php) without affecting the installation result.
